export const CALL_API = "CALL_API";
export const POST_ERROR = "POST_ERROR";
export const SUCCESS_SEARCH_BY_INGREDIENT_REQUEST =
  "SUCCESS_SEARCH_BY_INGREDIENT_REQUEST";
export const RECIPE_DETAIL = "RECIPE_DETAIL";
export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const DASHBOARD_VIDEO_ERROR = "DASHBOARD_VIDEO_ERROR";
export const DASHBOARD_VIDEO_API = "DASHBOARD_VIDEO_API";
export const SEARCH_VIDEO_ERROR = "SEARCH_VIDEO_ERROR";
export const SEARCH_VIDEO_API = "SEARCH_VIDEO_API";
